### ISSUE TITLE
Won't sim SoO Heirlooms*

### ISSUE THREAD

**Issue by rayfil** [seriallos/raidbots-issues#37] opened 2017-12-30 21:33 UTC
Tried to sim my character whilst levling with the Hellscream's Cleaver (id=104404) and it just won't sim, haven't tried with the other heirlooms but I suspect the bug also affects them as well. 

- It spits out the error msg: "Error that Seri forgot to handle".
- Have tried it on other browsers as just to see if it was a cache problem
- Tried swapping out the weapons to something that worked before in this case Venerable Dal'Rend's Sacred Charge (id=122351) and it worked fine.

**Comment by seriallos** [comment] 2018-01-05 17:58
Can you share your region/realm/character and/or SimC input that caused this? I'm unable to reproduce this issue right now.

**Comment by rayfil** [comment] 2018-01-05 18:09
I forgot to mention that the simulation was with stat-scaling on.

Here's the simc input I used: rogue="Anastealth"
level="93"
race="blood_elf"
region="eu"
server="draenor"
role="attack"
talents="3131310"
spec="outlaw"
head=",id=122248,bonus_id=3592"
neck=",id=153130,enchant_id=5439,bonus_id=3592"
shoulder=",id=122358,enchant_id=4804,bonus_id=3592"
back=",id=122261,enchant_id=5311,bonus_id=3592"
chest=",id=122383,enchant_id=4419,bonus_id=3592"
tabard=",id=83080"
wrist=",id=109868,bonus_id=518"
hands=",id=106138"
waist=",id=106135,bonus_id=171"
legs=",id=122254,bonus_id=3592"
feet=",id=106136"
finger1=",id=128173,enchant_id=5325,bonus_id=3592"
finger2=",id=109762,bonus_id=518"
trinket1=",id=128318"
trinket2=",id=122361,bonus_id=582"
main_hand=",id=104404,enchant_id=5331,gem_id=32194/32194"
off_hand=",id=104404,enchant_id=5331,gem_id=32194/32194"

**Comment by seriallos** [comment] 2018-01-05 18:29
Thank you for the simc input! That made it easy to find the bug (was treating a weapon with gems as a legion artifact, not a "normal" weapon).

Should be fixed and available on the site within 30 minutes or so.

**Closed by seriallos** 2018-01-05 18:29 UTC
Labels: bug, cant-repro
