### ISSUE TITLE
Blank white square in middle of pages.

### ISSUE THREAD

**Issue by orcphelia** [seriallos/raidbots-issues#36] opened 2017-12-15 20:30 UTC
There is a blank, white square in the middle left of all the pages. it is preventing me from pasting info into the simc box.

**Comment by seriallos** [comment] 2017-12-15 21:21
Hmm, I'm not seeing this on my own machine. Can you provide some more details to help me figure it out?

* A screenshot would be awesome
* What browser are you using?
* Are you a patron?
* Do you run any ad/script blocking software?

My quick guess is a bad ad if you're not running any ad blocking software. You might try using an ad blocker to see if that fixes the issue.

**Comment by orcphelia** [comment] 2017-12-16 00:14
I use Ad Block Plus. 
![simbot](https://user-images.githubusercontent.com/34584634/34065045-b817e3a4-e1c3-11e7-9219-2079571d3556.PNG)

**Comment by seriallos** [comment] 2017-12-16 00:22
What browser?

Does it still happen if you pause AdBlock Plus?

**Comment by orcphelia** [comment] 2017-12-16 01:20
Chrome. It's doing it intermittently. disabling the ad blocker hasn't seemed to make a difference. weird, huh? lol

**Comment by seriallos** [comment] 2017-12-16 01:58
Is it always in the same place? If you scroll up and down the page, does it move or stay stuck to the middle left?

Is it just Raidbots or does it happen on any other site?

Do you run any other extensions in Chrome that you could try disabling?

**Comment by orcphelia** [comment] 2017-12-16 05:30
just raidbots, and, yes, it stays in the same place. It's not doing it atm, though.

**Comment by seriallos** [comment] 2017-12-16 07:07
I haven't heard of anyone else having the issue so it's either pretty rare or has something to do with your machine/internet connection. My guess is that it's either related to ads on the site or something with your ISP but it's difficult to diagnose since I can't reproduce it.

One thing you could do if it happens again is to gather some more information:

In Chrome, right click in the white rectangle and click Inspect. That will open the developer console and should focus on the area of the HTML where it's coming from. Resize the dev console to be as large as possible while also including some of the Console area and take a screenshot of that.

Could also send me your username on the site and I can bump you up to the No Ads level which should remove all the possibly gross JS running on the page. If it's still happening at that level, we can potentially keep digging into the developer tools to see if there's a smoking gun there.

**Comment by orcphelia** [comment] 2017-12-18 00:57
It doesn't seem to be doing it now. Thanks for your swift responses. I really appreciate that. :)

**Comment by seriallos** [comment] 2018-01-05 17:51
Closing this out. Please let me know if it reoccurs and we can try debugging it some more.

**Closed by seriallos** 2018-01-05 17:51 UTC
