### ISSUE TITLE
Top Gear Sim fails on time out

### ISSUE THREAD

**Issue by gazer103** [seriallos/raidbots-issues#401] opened 2023-04-09 17:55 UTC
# If your bug is related to an incorrect tooltip, check the Full HTML Results before reporting! https://github.com/seriallos/raidbots-issues/issues/288

**Describe the bug**
When selecting the option to sim for top gear, it will sit on that page and think with the green spinning wheel.  90% of the time it will come back with an error stating it has failed due to connectivity issues.

**To Reproduce**
1. Go to Top Gear
2. Select a build and pick Sim
3. Will think for anywhere from 30 sec to 5 minutes and then time out due to "connectivity issue"

**Expected behavior**

**Link a sim with the problem (if available)**

If you have a sim report that shows the problem, please provide the URL here

**Character or /simc input**

For "Load from Armory":

* Region (US, EU, etc)
* Realm / Server
* Character Name

For "Load from SimC Addon":

Paste your /simc input

```
# Bamboogazer - Protection - 2023-04-09 13:55 - US/Bloodhoof
# SimC Addon 10.0.7-04
# WoW 10.0.7.48966, TOC 100007
# Requires SimulationCraft 1000-01 or newer

warrior="Bamboogazer"
level=70
race=pandaren
region=us
server=bloodhoof
role=tank
professions=blacksmithing=100/mining=100
spec=protection

talents=BkEAoonA2h02U1PVo4204nicFIEBAAAASSSkkg0SKJJpVQEIUESUSSACkkQDJJIARCAAAAAAAEBAo0aAgA

# Saved Loadout: Raid/ST
# talents=BkEAoonA2h02U1PVo4204nicFIEBAAAASSikkg0SKSSaNEBCFhQJJBIikkQDJJgAhAAAAAAAAJBAo0aAgA
# Saved Loadout: Raid/AoE
# talents=BkEAoonA2h02U1PVo4204nicFIEBAAAASSSkkg0SKJJpVQEIUESUSSACSSCNkkACECAAAAAAAEBAo0aAgA
# Saved Loadout: Mythic Murlok.IO
# talents=BkEAoonA2h02U1PVo4204nicFIEBAAAASSSkkg0SKJJpVQEIUESUSSACkkQDJJIARCAAAAAAAEBAo0aAgA
# Saved Loadout: Raz Int Happy
# talents=BkEAoonA2h02U1PVo4204nicFIEBAAAASSSkkg0SKJJpVQEIUESUSSACSSCNkkAARCAAAAAAAEBAo0aAgA

head=,id=200426,bonus_id=6652/7936/8828/7977/8973/1489/8767
neck=,id=193001,gem_id=192935/192935/192935,bonus_id=8836/8840/8902/8960/8784/8782/8802/8792/8846,crafted_stats=36/49
shoulder=,id=200428,bonus_id=6652/8826/8973/7977/1489/8767
back=,id=193712,enchant_id=6598,bonus_id=7977/6652/8822/8819/9144/8973/1637/8767
chest=,id=193644,enchant_id=6625,bonus_id=7977/6652/8822/8820/9144/8973/1637/8767
shirt=,id=151116
tabard=,id=43154
wrist=,id=109878,enchant_id=6580,gem_id=192935,bonus_id=7977/6652/8822/8819/9144/8780/8973/3300/8767
hands=,id=200425,bonus_id=6652/7977/8829/8973/1492/8767
waist=,id=191623,bonus_id=8836/8840/8902/8960/7937/8802/8846
legs=,id=200427,enchant_id=6490,bonus_id=6652/9130/7977/8827/1504
feet=,id=137482,enchant_id=6612,bonus_id=8974/7977/6652/8822/8818/9144/3297/8767
finger1=,id=134542,enchant_id=6556,gem_id=192935,bonus_id=9130/7977/6652/9144/3300/8767/8780
finger2=,id=203460,enchant_id=6556,gem_id=204013/204027/204029,gem_bonus_id=9369:1472/9369:1472/9369:1472,bonus_id=1491
trinket1=,id=194301,bonus_id=6652/7980/1485/8767
trinket2=,id=137486,bonus_id=7977/6652/9144/8973/3294/8767
main_hand=,id=190509,enchant_id=6642,bonus_id=8836/8840/8902/8802/8846/8792/8174,crafted_stats=32/49
off_hand=,id=190503,bonus_id=8836/8840/8902/8802/8846/8792,crafted_stats=36/40

### Gear from Bags
#
# Seal of Filial Duty (418)
# finger1=,id=195526,enchant_id=6568,gem_id=192935,bonus_id=6652/7935/7980/1485/8767
#
# Onyx Annulet (424)
# finger1=,id=203460,enchant_id=6556,gem_id=204007/204012/204022,gem_bonus_id=9369:1472/9369:1472/9369:1472,bonus_id=1491
#
# Seal of Diurna's Chosen (395)
# finger1=,id=195480,enchant_id=6556,bonus_id=6652/7936/7979/1472/8767
#
# Bonemaw's Big Toe (385)
# trinket1=,id=110012,bonus_id=8964/7977/6652/9144/3270/8767
#
# All-Totem of the Master (395)
# trinket1=,id=194306,bonus_id=7979/6652/1472/8767
#
# Blazebinder's Hoof (415)
# trinket1=,id=193762,bonus_id=7977/6652/9144/8973/1637/8767
#
# Bonemaw's Big Toe (398)
# trinket1=,id=110012,bonus_id=8968/7977/6652/9144/3283/8767
#
# Decoration of Flame (402)
# trinket1=,id=194299,bonus_id=7980/42/1485/8767
#
# Obsidian Seared Crusher (405)
# main_hand=,id=190516,enchant_id=6642,bonus_id=8836/8840/8902/8802/8845/8793,crafted_stats=49/32
#
# Nhallish's Bloody Polearm (415)
# main_hand=,id=110036,enchant_id=6642,bonus_id=8973/7977/6652/9147/3300/8767

# Checksum: 37fe9575
```

**Screenshots**

**Additional context**
I have not been able to find any connectivity issues with my connection and have no issues with any other software.  No lag in games, no buffering issues in video streaming and multiple functions can be going in parallel with no drop in performance.  I have attempted this sim both with the computer under load as well as with only the Raidbot page open with similar issues.  I have been able to recreate this issue in Chrome, Firefox and Microsoft Edge.  This is really annoying.  I have been a sub for a while now and use this page regularly.  It has only recent began to cause me issue and it prevents me from being able to check my gear for raid progression.  Please help me figure out this issue!

**Comment by seriallos** [comment] 2023-04-09 20:17
Quick guess would be something like Intel Killer Intelligence Center or some other 3rd party browser extension or Windows application that is causing a problem with the report loading. I'm able to run Top Gear sims for your character without issue (https://www.raidbots.com/simbot/report/dCxFgxfhgjMqW2n23gEUvt and https://www.raidbots.com/simbot/report/2v2TZwdcPqhkVGDMmkSVTR) and I'm not seeing any widespread issues.

If you haven't already, check this support article and try the steps listed there: https://support.raidbots.com/article/46-general-troubleshooting

That article will take you through trying different steps to try to pinpoint the issue.

I can't reproduce the issue so I'm closing the issue.

**Closed by seriallos** 2023-04-09 20:17 UTC
Labels: bug
