### ISSUE TITLE
Require tier not working correctly

### ISSUE THREAD

**Issue by cyberratt** [seriallos/raidbots-issues#332] opened 2022-04-05 16:07 UTC
When simming great vault options, I cannot sim a specific set of great vault non-tier gloves due to item restrictions.

https://i.imgur.com/tBmyOs0.png

My gear selections here DO allow for a 4 piece to be used, even though "no pieces required" is selected for tier requirements. One of the 4 tier pieces is a great vault option (chest) and it's the only piece selected for that slot. Oddly enough, one non-tier gloves is ok for a sim, but the 278 great vault option is not available for simming.

**Comment by seriallos** [comment] 2022-04-05 16:44
This is by design - when simming Great Vault items, only one GV item will be included in a combination since you can only choose 1 reward from the vault. Top Gear won't make a combination that has both the gloves and the chest since you can't receive both of them from the vault this week.

**Closed by seriallos** 2022-04-05 16:44 UTC
Labels: by-design
