### ISSUE TITLE
Domination Shard bonuses require you be in the Maw

### ISSUE THREAD

**Issue by cwagrant** [seriallos/raidbots-issues#301] opened 2021-08-03 22:34 UTC
**Describe the bug**
Attempted to sim my character, noticed the numbers were way off from a sim a few hours earlier. Earlier sim was while I was in Korthia(The Maw), most recent was in my covenant sanctum.

**To Reproduce**
1. use SimC addon in WoW to generate output while in The Maw with a Domination Shard set bonus active.
2. Run Quick Sim with the output on a Patchwerk fight.
3. Use SimC addon in WoW to generate output while in a maw where the buff from the Domination Shard set bonus will not be active (e.g. Oribos)
4. Run a Quick Sim with the output on a Patchwerk fight.

**Expected behavior**
I would expect the numbers to be relatively close and for the Dom Socket set bonus to be calculated in regardless of location depending on what I have selected in additional options.

**Link a sim with the problem (if available)**
In the Maw
https://www.raidbots.com/simbot/report/9faT1pwBaXVdR1Pr4NGfcY

Out of the Maw
https://www.raidbots.com/simbot/report/rEhmUshK69y6SPRD5JBR57

If you have a sim report that shows the problem, please provide the URL here

**Character or /simc input**

For "Load from Armory":

* Region (US, EU, etc)
* Realm / Server
* Character Name

For "Load from SimC Addon":

Paste your /simc input

**Screenshots**

**Additional context**

**Comment by seriallos** [comment] 2021-08-03 22:56
I am unable to reproduce this - I had no issues with my /simc output doing a quick run from Org -> Oribos -> Maw -> Korthia -> Ardenweald

Looks like the two /simc inputs were generated about two hours apart and one of them includes an additional soulbind talent that was unlocked. The later one also doesn't have any Domination Shards equipped - did you remove them to upgrade / test things out and forget to put them back into your gear?

**Comment by cwagrant** [comment] 2021-08-04 05:38
I hadn't touched/removed them. The second one I had just logged in, did a /simc, and then went to get the results. I logged in just for that purpose, now that I think of it. Because I realized I'd have the extra trait and wanted to see what it was worth.  Maybe because I hadn't opened my bags or character window the client hadn't made the shard info available to the simcraft addon. I'll have to test further.

**Comment by seriallos** [comment] 2021-08-04 07:41
There might be something funky that can happen if you run /simc right when you log on. There were occasional reports of issues with relics back in Legion - relics were just fancy sockets/gems so there might be something similar with domination shards. It's very rare (maybe a half dozen reports over ~4 years) and I've never been able to reproduce it myself.

**Comment by seriallos** [comment] 2021-08-10 19:38
Going to close this for now since I think this a WoW bug - if you can figure out a way to consistently reproduce the problem I can take a deeper look.

My best guess is that there's some race condition in the WoW Lua that results in no gems showing up in some rare conditions shortly after login. The bigger problem even if I can reproduce the problem is that I don't think there's any way an addon can detect or correct this scenario - it just looks like the item has an empty socket since the API isn't throwing an error.

**Closed by seriallos** 2021-08-10 19:38 UTC
Labels: bug
