### ISSUE TITLE
Top Gear Selects Invalid Gem Combinations

### ISSUE THREAD

**Issue by raphaelsk** [seriallos/raidbots-issues#143] opened 2019-08-16 03:29 UTC
**Scenario:**
Ran Top Gear sim. Currently equipped gear included a 
- Socketed Leadplate Legguards with a +120 Strength Gem
- Non-socketed Parrotfeather Cloak

Sim included the following gear from bags:
- Socketed Drape of the Hatcher with a +120 Strength Gem
- Socketed Sharkwater Waders with a +50 Haste gem

Did not allow changing existing gems/enchants.

**What happened?**
The Top Gear report selected a gear combination that used both items with +120 strength gems as the "Top Gear" set. Of course, such an equipment set cannot actually be equipped.

**What should have happened?**
The Top Gear report should have excluded the invalid gear combination from consideration and inclusion in the report.

**Comment by seriallos** [comment] 2019-08-16 15:48
Can you post your /simc input and a screenshot of your gem/enchant options?

**Comment by raphaelsk** [comment] 2019-08-17 02:08
Simc input (from the report page):
[simc input.txt](https://github.com/seriallos/raidbots-issues/files/3511562/simc.input.txt)

![ScreenShot Raidbots Simulation Options](https://user-images.githubusercontent.com/3611497/63205450-4d779c80-c072-11e9-847d-c656d8bbd294.png)

**Comment by raphaelsk** [comment] 2019-08-17 02:09
![Screenshot Gems Enchants Options](https://user-images.githubusercontent.com/3611497/63205471-8adc2a00-c072-11e9-98b8-b817cc447074.png)

**Comment by seriallos** [comment] 2019-08-17 02:10
Oh actually, do you have a link to the sim itself? That's even easier for me to check

**Comment by seriallos** [comment] 2019-08-17 02:14
Actually, info provided let me reproduce the issue. Looks like an issue in the combination code that isn't properly checking existing gems.

**Comment by seriallos** [comment] 2019-08-17 04:56
Fixed now. Thanks for the report!

**Closed by seriallos** 2019-08-17 04:56 UTC
