### ISSUE TITLE
Overclocking Bit Band

### ISSUE THREAD

**Issue by WarrzyO** [seriallos/raidbots-issues#361] opened 2022-11-13 22:43 UTC
**Describe the bug**

The bug is that the Overclocking Bit Band in retail have 109 haste bonus when at 298 and when I'm going to sim it it has 88 haste. So if you can do something about it then it would be great.

**Link a sim with the problem (if available)**

```
# Thelei - Unholy - 2022-11-13 23:33 - EU/Dentarg
# SimC Addon 10.0.0-3
# WoW 10.0.0.46597, TOC 100000
# Requires SimulationCraft 1000-01 or newer

deathknight="Thelei"
level=60
race=blood_elf
region=eu
server=dentarg
role=attack
professions=blacksmithing=100/mining=150
spec=unholy

talents=BwPAU3BjZ/IAySQ6AmAmsjvQ+BAIhkwBSLSQISECkkEJAAAAAAAAAAQSCkkGAApJlQSSOgkA

# Saved Loadout: Raid
# talents=BwPAU3BjZ/IAySQ6AmAmsjvQ+BAIhkwBSJSQISECkkEJAAAAAAAAAgCEJCAAIRKSJRSSikA
# Saved Loadout: Diseases  M+
# talents=BwPAU3BjZ/IAySQ6AmAmsjvQ+BAIhkwBSLSQISECkkEJAAAAAAAAAAQSCkkGAApJlQSSOgkA

covenant=night_fae
# soulbind=niya:1,322721/65:11:1/342270/70:11:1/320687/283:11:1/124:11:1/320660/250:11:1/352502/99:11:1/352503
soulbind=dreamweaver:2,319217/70:11:1/65:11:1/319211/124:11:1/283:11:1/319214/319191/250:11:1/352779/99:11:1/352786
# soulbind=korayn:6,325066/65:11:1/325067/70:11:1/325072/283:11:1/74:11:1/325069/124:11:1/352806/99:11:1/352805
# conduits_available=65:11/79:11/80:11/83:11/89:11/91:11/122:11/123:11/124:11/125:11/284:11/250:11/68:11/70:11/99:11/106:11/74:11/86:11/88:11/108:11/121:11/283:11
renown=80

head=,id=109988,gem_id=173130,bonus_id=7359/8258/8765/8136/8116/6652/3189/6646/7580
neck=,id=178927,gem_id=173130,bonus_id=6951/7882/8156/6647/6648/1588/6935
shoulder=,id=188867,bonus_id=6652/8759/8095/8152/1524
back=,id=142170,enchant_id=6202,bonus_id=8765/6652/7749/8136/8138/8284/3177/6646
chest=,id=188864,enchant_id=6230,bonus_id=7359/42/8153/8258/1524/6646
shirt=,id=18231
wrist=,id=186316,gem_id=173130,bonus_id=8759/6652/8132/8138/1550/6646/7580
hands=,id=188863,enchant_id=6210,bonus_id=6652/8272/7359/8765/8154/1524
waist=,id=185806,gem_id=173130,bonus_id=8765/8136/8137/7359/6652/8270/1615/6646/7580
legs=,id=188866,bonus_id=6652/8256/7359/8765/8155/1518
feet=,id=171413,enchant_id=6207,bonus_id=8119/7882/8156/6647/6648/1588
finger1=,id=169161,enchant_id=6168,gem_id=173130,bonus_id=7359/8286/8765/40/7580/3155/6646
finger2=,id=169159,enchant_id=6168,gem_id=173130,bonus_id=7359/8765/6652/7580/8284/3149/6646
trinket1=,id=188253,bonus_id=8764/6652/1537/6646
trinket2=,id=142167,bonus_id=8765/42/7749/8270/3177/6646
main_hand=,id=189862,enchant_id=3368,bonus_id=6652/8159/8764/1537/6646

### Gear from Bags
#
# Red Winter Hat (1)
# head=,id=21524
#
# Dingy Wizard Hat (12)
# head=,id=49201
#
# Unity (291)
# neck=,id=178927,gem_id=173130,bonus_id=8119/7882/8156/6648/6647/1588/6935
#
# Cloak of the Deadly Coil (291)
# back=,id=173242,enchant_id=6202,bonus_id=6952/6648/6649/8156/7882/1588
#
# Monstrosity Drapes (291)
# back=,id=173242,enchant_id=6202,bonus_id=6950/7882/8156/6648/6647/1588
#
# Red Winter Clothes (1)
# chest=,id=151790
#
# Endlessly Gluttonous Greaves (291)
# legs=,id=182992,bonus_id=8758/6652/8118/8116/1563/6646
#
# Winter Boots (1)
# feet=,id=151791
#
# Greaves of the First Eidolon (304)
# feet=,id=188865,enchant_id=6207,bonus_id=6652/8272/7359/8765/1524
#
# Seal of the Panoply (288)
# finger1=,id=185840,bonus_id=8281/8765/7359/6652/7579/7578/1605/6646
#
# The First Sigil (291)
# trinket1=,id=188271,bonus_id=6652/8758/1537/6646
#
# Inscrutable Quantum Device (272)
# trinket1=,id=179350,bonus_id=7359/6652/7784/1586/6646
#
# Necromedes, the Death Resonator (210)
# main_hand=,id=151255,bonus_id=7915,drop_level=60
#
# The Horseman's Sinister Slicer (236)
# main_hand=,id=117356,bonus_id=8760,drop_level=60
#
# Blacksmith Hammer (1)
# main_hand=,id=5956
#
# "The Brokers Angle'r" (40)
# main_hand=,id=180136

# Checksum: f27b39d
```

**Comment by seriallos** [comment] 2022-11-13 23:19
Duplicate of https://github.com/seriallos/raidbots-issues/issues/288

Tooltips are from Wowhead and are just for reference. The sim is properly calculating the right amount.

I ran a Gear Compare of your character, swapped in a ring that will activate the Overclocking Bit Band (the profile you provided will not proc the ring), and looked at the detailed buff output of the sim: https://www.raidbots.com/simbot/report/nDTSgBC6nun5yXnmB9Qshc/simc

<img width="692" alt="image" src="https://user-images.githubusercontent.com/1010294/201549850-1f6c761c-e445-4878-a1b1-02a77373f8e2.png">

**Closed by seriallos** 2022-11-13 23:19 UTC
Labels: by-design

**Comment by WarrzyO** [comment] 2022-11-14 09:33
Ok, but I don't understand the report that you linked.

Den mån 14 nov. 2022 kl 00:19 skrev Dave Hendler ***@***.***>:

**Comment by seriallos** [comment] 2022-11-14 15:35
It's the detailed report that SimC generates contained lots of granular data about the sim. The image section I linked shows that the Overclocking Bit Band buff (which is gained when the ring procs) is giving 109 haste which is correct.

Is there something specific you don't understand?

**Comment by WarrzyO** [comment] 2022-11-14 15:56
Why the buff is the 88 haste on wowhead and not 109.

Den mån 14 nov. 2022 kl 16:35 skrev Dave Hendler ***@***.***>:

**Comment by WarrzyO** [comment] 2022-11-14 19:45
Yeah, probably.

Den mån 14 nov. 2022 kl 17:03 skrev Dave Hendler ***@***.***>:
