### ISSUE TITLE
Old character name autofills in Armory input

### ISSUE THREAD

**Issue by seriallos** [seriallos/raidbots-issues#122] opened 2019-04-09 15:51 UTC
I am having a problem as well for setting the default char name. I transferred to another server and now It always pops my old name. Tried to make a fake request with curl to https://www.raidbots.com/api/discord/user/settings with OK response but still showing old nickname. Even tried to change localstorage item to the new nickname but still not getting it

Example of the prob: https://giphy.com/gifs/raidbotsnameproblem-l2vsnyadj8jhOJOajT

_Originally posted by @gkopevski in https://github.com/seriallos/raidbots-issues/issues/76#issuecomment-481165472_

**Comment by seriallos** [comment] 2019-04-09 15:59
What browser are you using and are you running a password manager? This look like a browser or extension autofill issue.

Check your browser or password manager to see if your old character name is attached to anything on the site.

You can also try using the reset tool (https://www.raidbots.com/reset) but I'd bet it won't change anything.

**Comment by gkopevski** [comment] 2019-04-10 13:38
I am using Lastpass as a password manager, but it is not the issue. What you pinpointed though is that I am localizing the issue slowly. On my home PC I don't have this issue (using chrome and windows). But noticed that this is always happening on Macbook Pro (Chrome) when running sims from work. 

I can test this on Mac and can help in order to resolve this issue (if you are not able to test it on Mac). Tell me which scenarios you need and I can help out.

**Comment by seriallos** [comment] 2019-04-10 16:13
There's a good chance it is LastPass. Check this first:

* Open up your LastPass Vault
* Search for raidbots.com
* Edit your Raidbots entry (the wrench icon)
* Edit Form Fields (wrench icon again, bottom of the pop-up panel)

Look for an entry called `armorySearch` and delete that.

LastPass is extremely aggressive at trying to find/fill fields that look like login inputs and it's very possible at some point in the past it guessed that the character name field was a login field.

If that doesn't work let me know and we can debug further.

**Comment by gkopevski** [comment] 2019-04-10 19:42
Will check tomorrow on my Mac and will write if it works, since on windows Chrome it is working. ty for this

**Comment by gkopevski** [comment] 2019-04-11 07:18
Checked this morning on my Mac, it is working as intended. Basically, Lastpass on Mac with browser Chrome causes a problem to the raidbots. You can close this issue since it is resolved for me

**Closed** 2019-04-11 16:08 UTC
